/**
 * Seed data ported from the frontend's src/lib/mockData.ts so the API serves
 * the exact catalog the UI was designed around.
 * Course `instructorEmail` is resolved to a User ObjectId at seed time.
 */

export const SEED_USERS = [
  // ─── Admin (admin@codecranium.com / admin123) ──────────────────────────────
  {
    name: 'Admin',
    email: 'admin@codecranium.com',
    password: 'admin123',
    role: 'admin',
  },
  // ─── Instructors (<first>@codecranium.com / <first>123) ───────────────────
  {
    name: 'Sarah Chen',
    email: 'sarah@codecranium.com',
    password: 'sarah123',
    role: 'instructor',
    bio: 'Senior frontend engineer with 10+ years building production React apps at scale.',
    payoutAccount: 'sarah_chen@paypal.me',
  },
  {
    name: 'Marcus Webb',
    email: 'marcus@codecranium.com',
    password: 'marcus123',
    role: 'instructor',
    bio: 'Systems programmer and open-source contributor. Loves Go, Rust, and distributed systems.',
  },
  {
    name: 'Priya Nair',
    email: 'priya@codecranium.com',
    password: 'priya123',
    role: 'instructor',
    bio: 'Data scientist turned educator. Makes Python and ML approachable for everyone.',
  },
  {
    name: 'Leo Vasquez',
    email: 'leo@codecranium.com',
    password: 'leo12345',
    role: 'instructor',
    bio: 'Full-stack engineer specializing in Node.js microservices and API design.',
  },
  // ─── Sample learners (password: learner123) ────────────────────────────────
  { name: 'Alex Rivera', email: 'alex@example.com', password: 'learner123', role: 'learner', plan: 'Pro', xp: 4200, streak: 5 },
  { name: 'Jamie Wu', email: 'jamie@devmail.io', password: 'learner123', role: 'learner', plan: 'Pro', xp: 8740, streak: 12 },
  { name: 'Dev Patel', email: 'dev@techco.com', password: 'learner123', role: 'learner', plan: 'Free', xp: 2100 },
  { name: 'Mia Torres', email: 'mia@startup.io', password: 'learner123', role: 'learner', plan: 'Team', xp: 6300, streak: 3 },
  { name: 'Lena Fischer', email: 'lena@company.de', password: 'learner123', role: 'learner', plan: 'Pro', xp: 12400, streak: 21 },
  { name: 'Carlos Mendez', email: 'carlos@mx.dev', password: 'learner123', role: 'learner', plan: 'Pro', xp: 15200, streak: 30 },
  { name: 'Ryo Tanaka', email: 'ryo@design.jp', password: 'learner123', role: 'learner', plan: 'Free', xp: 1800, status: 'inactive' },
  { name: 'Viktor Petrov', email: 'viktor@ru.dev', password: 'learner123', role: 'learner', plan: 'Pro', xp: 3900, status: 'banned' },
]

export const SEED_COURSES = [
  {
    slug: 'javascript-fundamentals',
    title: 'JavaScript Fundamentals',
    description: 'Master the core language: closures, prototypes, async/await, and the event loop explained from first principles.',
    longDescription: "This course takes you from absolute beginner to confident JavaScript developer. You'll understand not just how to use JavaScript, but why it works the way it does — closures, the prototype chain, the event loop, and more.",
    category: 'javascript',
    difficulty: 'beginner',
    duration: 480,
    rating: 4.8,
    reviewCount: 2341,
    students: 18450,
    price: 0,
    gradient: 'from-yellow-500 to-orange-500',
    instructorEmail: 'sarah@codecranium.com',
    tags: ['javascript', 'web', 'es6', 'async'],
    whatYouLearn: [
      'Understand scope, closures, and the prototype chain',
      'Write clean async code with Promises and async/await',
      'Master the event loop and how JavaScript runs',
      'Build interactive UIs with DOM manipulation',
      'Handle errors gracefully with try/catch and custom errors',
      'Use modern ES6+ features confidently',
    ],
    sections: [
      {
        title: 'Getting Started',
        lessons: [
          { slug: 'what-is-javascript', title: 'What is JavaScript?', duration: 8, type: 'article', isPreview: true },
          { slug: 'variables-and-types', title: 'Variables & Data Types', duration: 12, type: 'article', isPreview: true },
          { slug: 'operators-and-expressions', title: 'Operators & Expressions', duration: 10, type: 'challenge', isPreview: false },
        ],
      },
      {
        title: 'Functions & Scope',
        lessons: [
          { slug: 'functions-deep-dive', title: 'Functions Deep Dive', duration: 20, type: 'article', isPreview: false },
          {
            slug: 'closures', title: 'Closures Explained', duration: 18, type: 'article', isPreview: false, codeLanguage: 'javascript',
            starterCode: '// What does this function return?\nfunction makeCounter() {\n  let count = 0\n  return function() {\n    return ++count\n  }\n}\n\nconst counter = makeCounter()\nconsole.log(counter()) // ?',
          },
          { slug: 'scope-quiz', title: 'Scope Quiz', duration: 10, type: 'quiz', isPreview: false },
        ],
      },
      {
        title: 'Async JavaScript',
        lessons: [
          { slug: 'event-loop', title: 'The Event Loop', duration: 22, type: 'article', isPreview: false },
          { slug: 'promises', title: 'Promises & Chaining', duration: 25, type: 'article', isPreview: false },
          { slug: 'async-await', title: 'async/await in Practice', duration: 20, type: 'challenge', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'javascript',
  },
  {
    slug: 'react-mastery',
    title: 'React Mastery',
    description: 'Build production-grade React apps: hooks, context, performance, testing, and the new React 19 patterns.',
    longDescription: 'Go beyond tutorials. Learn to build fast, maintainable React applications the way senior engineers do — with proper state architecture, performance optimization, and a testing mindset.',
    category: 'react',
    difficulty: 'intermediate',
    duration: 720,
    rating: 4.9,
    reviewCount: 3102,
    students: 24100,
    price: 49,
    gradient: 'from-cyan-500 to-blue-500',
    instructorEmail: 'sarah@codecranium.com',
    tags: ['react', 'hooks', 'typescript', 'testing'],
    whatYouLearn: [
      'Master all React hooks and build custom ones',
      'Design scalable state with Zustand and Context',
      'Optimize renders with useMemo, useCallback, and Suspense',
      'Write tests with React Testing Library and Vitest',
      'Use React 19 Actions and the new use() API',
      'Build accessible components from scratch',
    ],
    sections: [
      {
        title: 'React Foundations',
        lessons: [
          { slug: 'thinking-in-react', title: 'Thinking in React', duration: 15, type: 'article', isPreview: true },
          { slug: 'jsx-and-rendering', title: 'JSX & Rendering', duration: 12, type: 'article', isPreview: true },
        ],
      },
      {
        title: 'Hooks In Depth',
        lessons: [
          { slug: 'use-state-patterns', title: 'useState Patterns', duration: 20, type: 'article', isPreview: false },
          { slug: 'use-effect-mastery', title: 'useEffect Mastery', duration: 25, type: 'challenge', isPreview: false },
          { slug: 'custom-hooks', title: 'Building Custom Hooks', duration: 30, type: 'challenge', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'typescript',
  },
  {
    slug: 'python-for-data-science',
    title: 'Python for Data Science',
    description: 'NumPy, Pandas, Matplotlib, and Scikit-learn — the full data science toolkit from data wrangling to model deployment.',
    longDescription: "Learn Python through the lens of real data problems. You'll go from data cleaning and visualization to training machine learning models, all on real-world datasets.",
    category: 'python',
    difficulty: 'beginner',
    duration: 600,
    rating: 4.7,
    reviewCount: 1890,
    students: 31200,
    price: 39,
    gradient: 'from-blue-500 to-indigo-500',
    instructorEmail: 'priya@codecranium.com',
    tags: ['python', 'data-science', 'ml', 'pandas'],
    whatYouLearn: [
      'Write clean, idiomatic Python code',
      'Manipulate data with Pandas like a pro',
      'Visualize data with Matplotlib and Seaborn',
      'Train and evaluate machine learning models',
      'Work with real datasets from Kaggle',
      'Deploy a model as a REST API',
    ],
    sections: [
      {
        title: 'Python Essentials',
        lessons: [
          { slug: 'python-basics', title: 'Python Basics', duration: 15, type: 'article', isPreview: true },
          { slug: 'lists-and-dicts', title: 'Lists & Dictionaries', duration: 12, type: 'challenge', isPreview: true },
        ],
      },
      {
        title: 'Data Wrangling',
        lessons: [
          { slug: 'pandas-intro', title: 'Intro to Pandas', duration: 25, type: 'article', isPreview: false },
          { slug: 'data-cleaning', title: 'Data Cleaning Techniques', duration: 30, type: 'challenge', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'python',
  },
  {
    slug: 'typescript-deep-dive',
    title: 'TypeScript Deep Dive',
    description: 'Type-level programming, generics, conditional types, and advanced patterns that make TypeScript truly powerful.',
    longDescription: 'Stop fighting TypeScript and start leveraging it. This course covers the type system in depth — generics, mapped types, template literal types, and the patterns used in large codebases.',
    category: 'typescript',
    difficulty: 'intermediate',
    duration: 540,
    rating: 4.8,
    reviewCount: 1456,
    students: 12300,
    price: 44,
    gradient: 'from-blue-600 to-violet-500',
    instructorEmail: 'sarah@codecranium.com',
    tags: ['typescript', 'type-system', 'generics'],
    whatYouLearn: [
      'Master generics and constraint patterns',
      'Write utility types from scratch',
      'Use conditional and mapped types',
      'Type complex async patterns correctly',
      'Configure tsconfig for strict mode',
      'Integrate TypeScript into any project',
    ],
    sections: [
      {
        title: 'Type System Foundations',
        lessons: [
          { slug: 'why-typescript', title: 'Why TypeScript?', duration: 10, type: 'article', isPreview: true },
          { slug: 'basic-types', title: 'Basic Types & Inference', duration: 18, type: 'article', isPreview: true },
        ],
      },
    ],
    codeLanguage: 'typescript',
  },
  {
    slug: 'nodejs-backend',
    title: 'Node.js Backend Development',
    description: 'Build production-ready REST APIs and microservices with Node.js, Express, Prisma, and PostgreSQL.',
    longDescription: 'Learn backend engineering the right way: clean architecture, proper error handling, authentication, rate limiting, and database design — all with Node.js and TypeScript.',
    category: 'nodejs',
    difficulty: 'intermediate',
    duration: 660,
    rating: 4.7,
    reviewCount: 987,
    students: 9800,
    price: 49,
    gradient: 'from-green-500 to-emerald-600',
    instructorEmail: 'leo@codecranium.com',
    tags: ['nodejs', 'express', 'prisma', 'postgresql', 'api'],
    whatYouLearn: [
      'Design RESTful APIs with Express and TypeScript',
      'Model data with Prisma and PostgreSQL',
      'Implement JWT authentication and refresh tokens',
      'Add rate limiting, logging, and error handling',
      'Write integration tests with supertest',
      'Deploy to production with Docker',
    ],
    sections: [
      {
        title: 'Node.js Internals',
        lessons: [
          { slug: 'node-event-loop', title: 'Node.js Event Loop', duration: 20, type: 'article', isPreview: true },
          { slug: 'modules-and-npm', title: 'Modules & npm', duration: 15, type: 'article', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'typescript',
  },
  {
    slug: 'css-architecture',
    title: 'CSS Architecture & Design',
    description: 'Modern CSS from layout fundamentals to design systems — Grid, Flexbox, animations, and component styling.',
    longDescription: 'CSS is underrated and undervalued. This course will make you the engineer who other engineers ask for design help — from layout systems to design tokens to animation.',
    category: 'css',
    difficulty: 'beginner',
    duration: 360,
    rating: 4.6,
    reviewCount: 743,
    students: 8900,
    price: 0,
    gradient: 'from-pink-500 to-rose-500',
    instructorEmail: 'sarah@codecranium.com',
    tags: ['css', 'design', 'flexbox', 'grid', 'animations'],
    whatYouLearn: [
      'Master Flexbox and CSS Grid completely',
      'Build responsive layouts without media query hacks',
      'Create smooth animations with keyframes and transitions',
      'Design and implement a component library',
      'Use CSS custom properties (variables) effectively',
      'Write maintainable CSS at scale',
    ],
    sections: [
      {
        title: 'Layout Fundamentals',
        lessons: [
          { slug: 'box-model', title: 'The Box Model', duration: 12, type: 'article', isPreview: true },
          { slug: 'flexbox-complete', title: 'Flexbox Complete Guide', duration: 25, type: 'challenge', isPreview: true },
        ],
      },
    ],
    codeLanguage: 'javascript',
  },
  {
    slug: 'go-backend',
    title: 'Go for Backend Engineers',
    description: 'Goroutines, channels, HTTP servers, and building high-performance APIs in Go from scratch.',
    longDescription: 'Go is the language of the cloud. This course teaches you to write idiomatic Go — concurrency patterns, the standard library, and building production-grade services.',
    category: 'go',
    difficulty: 'advanced',
    duration: 720,
    rating: 4.9,
    reviewCount: 612,
    students: 5400,
    price: 54,
    gradient: 'from-teal-400 to-cyan-600',
    instructorEmail: 'marcus@codecranium.com',
    tags: ['go', 'golang', 'concurrency', 'microservices'],
    whatYouLearn: [
      'Write idiomatic, clean Go code',
      'Master goroutines, channels, and the sync package',
      'Build HTTP servers with the standard library',
      'Design and implement gRPC services',
      'Write comprehensive tests and benchmarks',
      'Profile and optimize Go programs',
    ],
    sections: [
      {
        title: 'Go Fundamentals',
        lessons: [
          { slug: 'go-tour', title: 'A Tour of Go', duration: 20, type: 'article', isPreview: true },
          { slug: 'types-and-interfaces', title: 'Types & Interfaces', duration: 25, type: 'article', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'go',
  },
  {
    slug: 'rust-systems-programming',
    title: 'Rust Systems Programming',
    description: 'Ownership, borrowing, lifetimes, and systems-level programming — understand why Rust is the future of safe systems code.',
    longDescription: 'Rust is the most loved language for a reason. This course demystifies the borrow checker, teaches you to think in terms of ownership, and shows you how to write blazing fast, memory-safe code.',
    category: 'rust',
    difficulty: 'advanced',
    duration: 840,
    rating: 4.8,
    reviewCount: 489,
    students: 4100,
    price: 59,
    gradient: 'from-orange-500 to-red-500',
    instructorEmail: 'marcus@codecranium.com',
    tags: ['rust', 'systems', 'ownership', 'wasm'],
    whatYouLearn: [
      'Master ownership, borrowing, and lifetimes',
      'Write safe concurrent code without data races',
      'Use traits and generics effectively',
      'Build CLI tools and system utilities',
      'Compile Rust to WebAssembly',
      'Understand unsafe Rust and when to use it',
    ],
    sections: [
      {
        title: 'Ownership & Borrowing',
        lessons: [
          { slug: 'ownership-intro', title: 'The Ownership Model', duration: 25, type: 'article', isPreview: true },
          { slug: 'borrowing', title: 'References & Borrowing', duration: 22, type: 'article', isPreview: false },
        ],
      },
    ],
    codeLanguage: 'rust',
  },
]

// courseSlugs are resolved to Course ObjectIds at seed time
export const SEED_LEARNING_PATHS = [
  {
    slug: 'frontend-developer',
    title: 'Frontend Developer',
    description: 'Go from zero to shipping production React apps. HTML → CSS → JavaScript → TypeScript → React.',
    courseSlugs: ['css-architecture', 'javascript-fundamentals', 'typescript-deep-dive', 'react-mastery'],
    difficulty: 'beginner',
    totalHours: 66,
    icon: '⚡',
    gradient: 'from-indigo-500 to-purple-500',
  },
  {
    slug: 'backend-engineer',
    title: 'Backend Engineer',
    description: 'Build production APIs and services. Node.js → Go → databases → distributed systems.',
    courseSlugs: ['nodejs-backend', 'go-backend'],
    difficulty: 'intermediate',
    totalHours: 46,
    icon: '⚙️',
    gradient: 'from-green-500 to-teal-500',
  },
  {
    slug: 'systems-programmer',
    title: 'Systems Programmer',
    description: 'Low-level mastery. Go + Rust for performance-critical applications and infrastructure tooling.',
    courseSlugs: ['go-backend', 'rust-systems-programming'],
    difficulty: 'advanced',
    totalHours: 26,
    icon: '🦀',
    gradient: 'from-orange-500 to-red-500',
  },
  {
    slug: 'full-stack',
    title: 'Full-Stack Developer',
    description: 'Master both sides. Frontend with React + TypeScript, backend with Node.js — ship complete products.',
    courseSlugs: ['javascript-fundamentals', 'react-mastery', 'typescript-deep-dive', 'nodejs-backend'],
    difficulty: 'intermediate',
    totalHours: 84,
    icon: '🚀',
    gradient: 'from-blue-500 to-violet-500',
  },
]

// Resolved at seed time: authorEmail → User, courseSlug → Course
export const SEED_COMMENTS = [
  {
    authorEmail: 'alex@example.com',
    courseSlug: 'javascript-fundamentals',
    lessonSlug: 'closures',
    content: "The closure explanation finally clicked for me after watching this. I've read about it 10 times before but this framing is perfect.",
    status: 'approved',
    replies: [
      {
        authorEmail: 'sarah@codecranium.com',
        content: 'So glad it clicked! The mental model is everything with closures.',
      },
    ],
  },
  {
    authorEmail: 'jamie@devmail.io',
    courseSlug: 'react-mastery',
    lessonSlug: 'use-effect-mastery',
    content: 'The code challenges are genuinely hard in the best way. I tried to cheat and skip ahead and regretted it.',
    status: 'approved',
  },
  {
    authorEmail: 'viktor@ru.dev',
    courseSlug: 'javascript-fundamentals',
    lessonSlug: 'closures',
    content: 'This course is garbage, totally wrong explanation of closures. Do not waste your money.',
    status: 'pending',
    flagReason: 'Spam / abusive language',
  },
]
